### ISSUE TITLE
自定义配置文件被覆盖

### ISSUE THREAD

**Issue by yueduz** [fcitx/libime#12]
我在 ～/.local/share/fcitx5/inputmethod 目录中放了自定义码表输入法文件：cqyx.conf。可以在fcitx5配置工具中看到自定义输入法，但是点输入法配置后文件被覆盖，输入法提示不可用.

**Comment by yueduz** [comment]
输入法无效是我使用了相对路径。但是被配置工具修改过的文件时不应该放在这里 `https://github.https://github.com/fcitx/libime/issues/12com/fcitx/libime/issues/12https://github.com/fcitx/libime/issues/12

**Comment by wengxt** [comment]
就是设计成应该放那里的。没有问题。

**Comment by yueduz** [comment]
放在那里的话，如果我放一个文件cqyx.conf在那里
```
[InputMethod]
Name[da]=Cqyx
Name[de]=Cqyx
Name[ko]=Cqyx
Name[zh_CN]=超强音形
Name=Cqyx
Icon=fcitx-erbi
Label=二
LangCode=zh_CN
Addon=table
Configurable=True

[Table]
File=~/.local/share/libime/cqyx.main.dict
AutoSelect=True
AutoSelectLength=-1
NoMatchAutoSelectLength=0
Hint=False
OrderPolicy=Freq
UseFullWidth=True
QuickPhraseKey=semicolon
PinyinKey=[
MatchingKey=?
AutoPhraseLength=4
SaveAutoPhraseAfter=-1
UseContextRelatedOrder=False

[Table/PrevPage]
0=Up
1=minus

[Table/NextPage]
0=Down
1=equal
```
我点ui配置工具配置，`~/.local/share/fcitx5/inputmethod/cqyx.conf`就被覆盖了。点配置后应该是把`~/.local/share/fcitx5/inputmethod/cqyx.conf`复制到`～/.config/fcitx5/conf/cqyx.conf`
