### ISSUE TITLE
生僻字检索不到

### ISSUE THREAD

**Issue by tkkcc** [fcitx/libime#22]
"鋆"（音同均）可以在fcitx4中使用搜狗输入法检索到，但在fcitx5中无法通过Shuangpin或Pinyin方式检索到。
请问生僻字应该如何添加进检索库？

版本：
fcitx5-chinese-addons 5.0.3
fcitx5 5.0.4

**Comment by wengxt** [comment]
网络上查了一下这个字的读音，说法是人名中可以读作  jun，应该添加到数据里面

如果要现在自己添加的话，就写如下这样的文件
```
鋆 jun 0
```
用配置界面的导入

或者手工  libime_pinyindict 转换然后复制到 ~/.local/share/fcitx5/pinyin/dictionaries/ 文件名后缀为 .dict。

**Comment by tkkcc** [comment]
感谢！导入方法work。

**Comment by wengxt** [comment]
添加了一些缺失的读音。
