### ISSUE TITLE
kpu/kenlm need to update and add loongarch

### ISSUE THREAD

**Issue by HougeLangley** [fcitx/libime#32]
老K，晚上好，目前 fcitx/libime 引用的 kpu/kenlm 的 util/double-conversion/utils.h 没有定义龙芯架构，刚刚我发了 issue 给 kpu/kenlm 提示他需要更新，因为目前 google 的 double-conversion 已经定义了。咱去催促下，这样上游更新了，Arch 后续 fcitx5 也能用上。

https://github.com/kpu/kenlm/issues/386
https://github.com/google/double-conversion/blob/master/double-conversion/utils.h#L135
https://github.com/microcai/gentoo-zh/issues/2143

**Comment by wengxt** [comment]
@HougeLangley 这个主要还是得等上游merge了我才能更新submodule commit

**Comment by HougeLangley** [comment]
子模块更新了，麻烦老K帮我更新下

https://github.com/kpu/kenlm/issues/386

**Comment by HougeLangley** [comment]
Have been test in gentoo, build success.
