### ISSUE TITLE
Add option to disable fcitx5_download

### ISSUE THREAD

**Issue by easyteacher** [fcitx/libime#34]
To be able to build without Internet

**Comment by CoelacanthusHex** [comment]
AFAIK, you can just put the file in the proper position, and cmake will use it rather than downloading it.

**Comment by wengxt** [comment]
use  _dict tar, or predownload the file and put them to the right place. 

See how we do it for flatpak https://github.com/fcitx/flatpak-fcitx5/blob/master/modules/libime.yaml
