### ISSUE TITLE
使用拼音输入法查词占用较多资源导致系统卡死

### ISSUE THREAD

**Issue by rico256-cn** [fcitx/libime#45]
使用网上下的一个拼音词库

$du -sh *
38M     CustomPinyinDictionary_Fcitx.dict

按如下方式持续输入，fcitx5进程cpu和内存占用就持续升高，并且在我停止了输入的情况下（保持静止状态），输入就
完全卡死了。
请问怎么样限制输入的候选深度，防止这类事件发生。

其他的词库我还没测试。 

<img width="384" alt="image" src="https://user-images.githubusercontent.com/60219649/220914341-42db4cbc-7402-4f10-8fde-319d084defe1.png">

**Comment by wengxt** [comment]
和词典大小感觉没什么关系，感觉是某个能匹配到kkkkkk.... 的词正好触发了某种指数增长

**Comment by wengxt** [comment]
研究了一下，主要问题是 backwardSearch 存储了太多中间状态

![image](https://user-images.githubusercontent.com/259684/221014463-a55d763e-8e69-4fee-b539-9725cba05325.png)

**Comment by wengxt** [comment]
修复之前最简单的workaround办法就是你把配置里句子数量改成1

**Comment by rico256-cn** [comment]
谢谢，最好是能限制这类情况发生，不然用起来一不小心键盘长按系统就挂了。  另外请问在英文输入法状态时，键盘输入数据会过进程么？因为还有个输入时卡顿 case 不确定是否和输入法有关

**Comment by wengxt** [comment]
> 谢谢，最好是能限制这类情况发生，不然用起来一不小心键盘长按系统就挂了。 另外请问在英文输入法状态时，键盘输入数据会过进程么？因为还有个输入时卡顿 case 不确定是否和输入法有关

会，但不会过无关的代码

**Comment by rico256-cn** [comment]
@wengxt  新版我测试不会导致卡死了，不过还有个问题，就是 连续输入过快的时候，依旧能很明显的感觉到卡顿（cpu瞬间会飙的比较高）

**Comment by wengxt** [comment]
输入法的计算是复杂的。你编译选项要开 release 否则影响很大。

**Comment by rico256-cn** [comment]
@wengxt 请问 是
cmake -DCMAKE_INSTALL_PREFIX=/usr   -DENABLE_WAYLAND=OFF -DENABLE_EMOJI=OFF  -DCMAKE_BUILD_TYPE=Release .

加-DCMAKE_BUILD_TYPE=Release 这个参数把？

对比了一下同样make install/strip后的bin，确实大小不一样了。 😄
$du -sh /usr/bin/fcitx5
712K    /usr/bin/fcitx5

$du -sh /usr/bin/fcitx5
400K    /usr/bin/fcitx5

**Comment by wengxt** [comment]
libime用release比较重要，fcitx5不是很有所谓
