### ISSUE TITLE
双拼输入法 a ai ao

### ISSUE THREAD

**Issue by colorsakura** [fcitx/libime#46]
自然码双拼: 当输入`a`时, 候选词只有啊发音的词. 按道理应该可以匹配拼音 `a` `ai` `ao`这些词才对.
啊: 双拼 aa
爱: 双拼 ai
熬: 双拼 ao

**Comment by wengxt** [comment]
@colorsakura ios的双拼就没有这种功能

**Comment by colorsakura** [comment]
确实没有,我的.天天用ios的双拼也没考虑测试一下.
想请问一下,拼音模式下出现的 英语单词 的词库在那个位置呀, 想定制一下.
