### ISSUE TITLE
investigate remove boost regex from deps

### ISSUE THREAD

**Issue by wengxt** [fcitx/libime#48]
actually c++ has regex support and fcitx5 is already using it. I probably forgot c++11 has regex support when write this code..

**Comment by CoelacanthusHex** [comment]
However, libstdc++'s `std::regex` implementation has terrible performance in most case. That's because the developers of libstdc++ don't want to break ABI so the implementation can't be well optimized.

https://github.com/HFTrader/regex-performance/tree/master#results

**Comment by wengxt** [comment]
the usage in libime is not performance sensitive, so it is ok
