### ISSUE TITLE
导入用户词典允许跳过错误或者支持不完整拼音

### ISSUE THREAD

**Issue by ArcanusNEO** [fcitx/libime#49]
之前有使用ibus的libpinyin，其导出的用户词典存在类似 `包含 bao'h 5` 、 `命运石之门 ming'yun'shi'zhi'm 84` 这样不完整拼音形式的行，导入fcitx会报错。手动删除这些行不太现实，工作量太大。能否增加支持导入不完整拼音的功能？如果不行的话希望可以增加跳过错误行的逻辑。

**Comment by wisim3000** [comment]
> 正则表达式`^.*\b[a-z]\b.*$`确实能匹配到这些行，但是也能匹配到不应该删去的内容。 ![图片](https://user-images.githubusercontent.com/57259186/233270507-c861a137-7193-4d11-9470-68ea866dfd2b.png) 图片里的内容是运行 `grep -Ei '^.*\b[a-z]\b.*$' libpinyin_dict.txt | vi -` 得到的。

那就排除一下aeiou
`^.*\b[b-df-hj-np-tv-z]\b.*$`

**Comment by ArcanusNEO** [comment]
实际上还会有 `生产 sheng'ch 5` 这种形式的不完整拼音，匹配单字母的正则也无法处理。

**Comment by wisim3000** [comment]
> 实际上还会有 `生产 sheng'ch 5` 这种形式的不完整拼音，匹配单字母的正则也无法处理。

你删两次不行吗
`^.*\b(?=[a-z])[^aeo]\b.*$`
`^.*\b(zh|ch|sh)\b.*$`
这样。

另外，事实上大佬已经在最新的提交里忽略导入错误了。

**Comment by ArcanusNEO** [comment]
确实，谢谢。
