### ISSUE TITLE
「单」字作为姓氏时的读音shan不存在

### ISSUE THREAD

**Issue by CoelacanthusHex** [fcitx/libime#53]
如题，该字作为姓氏时读shan。
https://www.zdic.net/hans/%E5%8D%95

**Comment by rocka** [comment]
libime 1.1.1 试了一下有这个读音，你在用哪个版本？

![Screenshot.png](https://github.com/fcitx/libime/assets/13914967/060d1d27-290a-4a07-9362-b0af275d3f9d)

**Comment by CoelacanthusHex** [comment]
怪，可能是眼瞎了，刚刚找了好几遍都没看到

**Comment by CoelacanthusHex** [comment]
下次感觉看看调用 dbus 接口 grep 吧
