### ISSUE TITLE
clang+musl: joint_sort.hh:104:68: error: no template named 'binary_funct ion' in namespace 'std'

### ISSUE THREAD

**Issue by liangyongxiang** [fcitx/libime#57]
编译环境是 Gentoo clang + musl
完整日志： https://bpa.st/DTIA 或 https://gist.github.com/liangyongxiang/dbd008b3b7210d340b5d7f81b59069f8

现在使用的 workaround 是 ：https://github.com/microcai/gentoo-zh/issues/3051#issuecomment-1482871679

想请问一下，是否有更好的处理方式 ？

https://github.com/microcai/gentoo-zh/blob/master/app-i18n/libime/libime-1.1.3.ebuild#L41

**Comment by wengxt** [comment]
> 目测让 kenlm 声明自己使用的语言标准应该可以解决，不过我觉得 libime 最好也声明下自己用的语言标准

这里指定的全局标准
include("${FCITX_INSTALL_CMAKECONFIG_DIR}/Fcitx5Utils/Fcitx5CompilerSettings.cmake")
