### ISSUE TITLE
[双拼] 韵母位优先识别为按键字母而非绑定的韵母

### ISSUE THREAD

**Issue by UM-Li** [fcitx/libime#62]
你好，我在 `~/.config/fcitx5/pinyin/sp.dat` 有这些绑定：

```
[韵母]
o=Y
uo=Y
ie=O
```

测试发现 `PY` 能识别为 “po”，但 `PO` 也识别为 “po“ 而非 ”pie“。

```
[声母]
zh=V

[韵母]
ing=E
uai=E
e=F
```

`VF` 能识别为 “zhe”，但 `VE` 也识别为 “zhe” 而非 “zhuai”。

键盘布局是英语（美国）- Colemak，期望实现这样的自定义方案：
![小鹤双拼（Colemak 韵母）](https://github.com/fcitx/fcitx5/assets/6215580/854e94fe-705d-4fe2-b781-73d15fadbf51)

请问怎样让 Fcitx5 优先识别按键上绑定的韵母？

**Comment by wengxt** [comment]
请试一下最新的 git

**Comment by UM-Li** [comment]
最新 git 版本下这个布局能正常使用了，感谢！
