### ISSUE TITLE
仓颉码表繁简体问题

### ISSUE THREAD

**Issue by buthotthing** [fcitx/libime#69]
现在的仓颉码表似乎使用了繁简转换，将繁体字的码套用到简体字上面。
查看文件 [https://download.fcitx-im.org/data/table-20240108.tar.gz](https://download.fcitx-im.org/data/table-20240108.tar.gz) ->  `cj.txt`
```
...
agdi 时    # 正确编码: agdi=時, adi=时
aggu 晓    # 正确编码: aggu=曉, ajpu=晓
ahbr 晌
...
yxln 剂    # 正确编码: yxln=劑, ylln=剂
yy 卞
yymr 这    # 正确编码: yymr=這, yyk=这
...
```
仓颉输入法中，繁体字和简体字的编码大部分是不相同的。
现在这份码表繁体字没有收录，简体字的编码是错的，几乎就是不能用了。

希望换上正确的码表，谢谢。

**Comment by wengxt** [comment]
请用 table-extra里的仓颉
